/*
 * File: app/controller/AppLaunchCtrl.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.AppLaunchCtrl', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'tabPanel',
            selector: '#tabPanel'
        },
        {
            ref: 'outStockForm',
            selector: '#outStockForm'
        },
        {
            ref: 'inStockForm',
            selector: '#inStockForm'
        },
        {
            ref: 'staffQuery',
            selector: '#staffQuery'
        },
        {
            ref: 'departmentQuery',
            selector: '#departmentQuery'
        },
        {
            ref: 'unitQuery',
            selector: '#unitQuery'
        },
        {
            ref: 'categoryQuery',
            selector: '#categoryQuery'
        },
        {
            ref: 'stockQuery',
            selector: '#stockQuery'
        },
        {
            ref: 'inStockDetailOrderQuery',
            selector: '#inStockDetailOrderQuery'
        },
        {
            ref: 'inStockTotalQuery',
            selector: '#inStockTotalQuery'
        },
        {
            ref: 'outStockTotalQuery',
            selector: '#outStockTotalQuery'
        },
        {
            ref: 'outStockDetailOrderQuery',
            selector: '#outStockDetailOrderQuery'
        },
        {
        	ref:'departmentOutQuery',
        	selector: '#departmentOutQuery'
        },
        {
            ref: 'trendChart',
            selector: '#trendChart'
        },
        {
            ref: 'btns',
            selector: '#navi button'
        }
    ],

    onButtonInStockClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'InStockPanelCtrl', 'MyInStockPanel', '1');
    },
    
    onButtonOutStockClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'OutStockPanelCtrl', 'MyOutStockPanel', '2');
    },

    onButtonChartClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'ChartCtrl', 'MyChart', '3');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    
    onButtonUnitClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'UnitCtrl', 'MyUnit', '4');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },

    onButtonDepartmentClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'DepartmentCtrl', 'MyDepartment', '5');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    
    onButtonStaffClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'StaffCtrl', 'MyStaff', '6');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    
    onButtonCategoryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'CategoryCtrl', 'MyCategory', '7');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    
    onButtonStockClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'StockPanelCtrl', 'MyStockPanel', '8');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
 
    onButtonInStockQueryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'InStockDetailPanelCtrl', 'MyInStockDetailPanel', '9');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    
    onButtonOutStockQueryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'OutStockDetailPanelCtrl', 'MyOutStockDetailPanel', '10');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },

    onButtonInStockTotalQueryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'InStockTotalCtrl', 'MyInStockTotal', '11');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
 
    onButtonOutStockTotalQueryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'OutStockTotalCtrl', 'MyOutStockTotal', '12');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    
    onButtonDepartmentOutQueryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'DepartmentOutCtrl', 'MyDepartmentOutStock', '13');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    

    onButtonStockTotalByCategoryQueryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'StockTotalByCategoryCtrl', 'MyStockTotalByCategory', '14');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },
    
    
    unpressOtherBtns: function(exceptBtn) {
        var nextBtn = this.getBtns();
        while (nextBtn) {
            if (nextBtn.itemId !== exceptBtn.itemId && nextBtn.pressed) {
                console.log(nextBtn.itemId);
                nextBtn.toggle(true);
            }
            nextBtn = nextBtn.nextSibling("button");
        }

    },

    onControllerClickStub: function() {

    },

    init: function() {
        this.control({
            "#btnInStock": {
                click: this.onButtonInStockClick
            },
            "#btnOutStock": {
                click: this.onButtonOutStockClick
            },
            "#btnTrend": {
                click: this.onButtonChartClick
            },
            "#btnUnitQuery":{
            	click: this.onButtonUnitClick
            },
            "#btnDepartmentQuery":{
            	click: this.onButtonDepartmentClick
            },
            "#btnStaffQuery":{
            	click: this.onButtonStaffClick
            },
            "#btnCategoryQuery":{
            	click: this.onButtonCategoryClick
            },
            "#btnStockQuery":{
            	click: this.onButtonStockClick
            },
            "#btnInStockQuery":{
            	click: this.onButtonInStockQueryClick
            },
            "#btnOutStockQuery":{
            	click: this.onButtonOutStockQueryClick
            },
            "#btnInStockTotalQuery":{
            	click: this.onButtonInStockTotalQueryClick
            },
            "#btnOutStockTotalQuery":{
            	click: this.onButtonOutStockTotalQueryClick
            },
            "#btnDeparmentOutQuery":{
            	click: this.onButtonDepartmentOutQueryClick
            },
            '#btnStockTotalByCategoryQuery':{
            	click: this.onButtonStockTotalByCategoryQueryClick
            }
        });
    }
});