/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Viewport', {
    extend: 'MyApp.view.MyViewport',
    renderTo: Ext.getBody(),
    requires: [
        'MyApp.view.MyViewport',
        'MyApp.view.MyInStockGrid',
        'MyApp.view.MyInStockForm',
        'MyApp.view.MyInStockPanel',
        'MyApp.view.MyOutStockGrid',
        'MyApp.view.MyOutStockForm',
        'MyApp.view.MyOutStockPanel',
        'MyApp.view.MyQuery',
        'MyApp.view.MyChart',
        'MyApp.view.MyUnit',
        'MyApp.view.MyDepartment',
        'MyApp.view.MyStaff',
        'MyApp.view.MyCategory',
        'MyApp.view.MyStockPanel',
        'MyApp.view.MyStock',
        'MyApp.view.MyStockDetail',
        'MyApp.view.MyInStockDetailPanel',
        'MyApp.view.MyInStockDetailOrder',
        'MyApp.view.MyInStockDetail',
        'MyApp.view.MyInStockTotal',
        'MyApp.view.MyOutStockDetailPanel',
        'MyApp.view.MyOutStockDetailOrder',
        'MyApp.view.MyOutStockDetail',
        'MyApp.view.MyOutStockTotal',
        'MyApp.view.MyDepartmentOutStock',
        'MyApp.view.MyStockTotalByCategory'
    ]
});